// Generated by hand to match supabase/migrations/0001_init.sql.
// When the schema changes, regenerate with `supabase gen types typescript`
// and replace this file.

import type { SourceCategory, SourceType } from "@/data/sources";

export type ContentType =
  | "article"
  | "video"
  | "podcast-episode"
  | "gallery-item";

export type SourceRow = {
  id: string;
  slug: string;
  name: string;
  url: string;
  feed_url: string | null;
  type: SourceType;
  category: SourceCategory;
  icon_url: string | null;
  initials: string | null;
  swatch: string | null;
  youtube_channel_id: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type SourceInsert = Omit<
  SourceRow,
  "id" | "created_at" | "updated_at"
> & {
  id?: string;
};

export type ArticleRow = {
  id: string;
  source_id: string;
  title: string;
  original_url: string;
  summary: string | null;
  thumbnail_url: string | null;
  author: string | null;
  published_at: string | null;
  fetched_at: string;
  read_minutes: number | null;
  duration_minutes: number | null;
  category: SourceCategory;
  content_type: ContentType;
  is_featured: boolean;
  is_must_read: boolean;
  raw_content: string | null;
  content_hash: string | null;
  created_at: string;
};

export type ArticleInsert = Omit<
  ArticleRow,
  "id" | "fetched_at" | "created_at"
> & {
  id?: string;
  fetched_at?: string;
};

export type EditionRow = {
  id: string;
  edition_date: string;
  hero_article_id: string | null;
  editors_pick_id: string | null;
  created_at: string;
  updated_at: string;
};

// The Database shape must satisfy supabase-js's GenericSchema (Tables,
// Views, Functions all present, each table carrying a Relationships array).
// We have no DB views or functions yet, so those are empty Records.
export type Database = {
  public: {
    Tables: {
      sources: {
        Row: SourceRow;
        Insert: SourceInsert;
        Update: Partial<SourceInsert>;
        Relationships: [];
      };
      articles: {
        Row: ArticleRow;
        Insert: ArticleInsert;
        Update: Partial<ArticleInsert>;
        Relationships: [
          {
            foreignKeyName: "articles_source_id_fkey";
            columns: ["source_id"];
            referencedRelation: "sources";
            referencedColumns: ["id"];
          }
        ];
      };
      editions: {
        Row: EditionRow;
        Insert: Omit<EditionRow, "id" | "created_at" | "updated_at"> & {
          id?: string;
        };
        Update: Partial<Omit<EditionRow, "id" | "created_at" | "updated_at">>;
        Relationships: [
          {
            foreignKeyName: "editions_hero_article_id_fkey";
            columns: ["hero_article_id"];
            referencedRelation: "articles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "editions_editors_pick_id_fkey";
            columns: ["editors_pick_id"];
            referencedRelation: "articles";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};
